### ISSUE TITLE
ASP core 6 with Grape js newsletter

### ISSUE THREAD

**Issue by fasteddys** [gordon-matt/MantleCMS#5]
Hello, this is a hidden gem!!! 🥇 

- Any chance you can get a module/code generator or we can get boilerplate going for menu, localization, authorization etc hooks.
- Also I tried to upgrade to .net core 6 and failed, how can I get this to run on a linux box.
- Lastly themes, how to apply themes easily
- I am trying to build a dashboard, where to start, is there a lifecycle or architecture drawing for this.

**Comment by gordon-matt** [comment]
Thanks for your kind words. As per the details in the README, it's not really polished off and has some issues that need to be worked out. If you're looking for something more stable, I would recommend the older [KoreCMS](https://github.com/gordon-matt/KoreCMS), which this one is based on.. but of course that's written in the older MVC 5.

I don't have much time to work on Mantle myself these days, but feel free to make fixes or add features as you like. I'd be happy to review any pull requests.
